name: Munch workflow
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Install packages
        run: |
          cd frontend
          npm i

      - name: Run test
        run: |
          cd /home/runner/work/munch/frontend
          npm run test:ci -- -u

      - name: Test Reporter
        uses: dorny/test-reporter@v1.8.0
        if: success() || failure()
        with:
          name: Test Results
          path: 'frontend/test-results/*.xml'
          reporter: jest-junit

      - name: Prettify frontend code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write "**/*.{js,md,ts,tsx}" --tab-width 2 --print-width 80 --single-quote true --jsx-single-quote true --end-of-line lf
          only_changed: True

      - name: Prettify backend code
        uses: psf/black@stable
        with:
          options: "--verbose"
          src: "./backend"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
